baseUrl = "https://graciousgrey.gitlab.io/"
languageCode = "en-us"
relativeURLs = true
contentDir    = "content"
layoutDir     = "layouts"
publishDir    = "public"
canonifyurls  = true
title = "Theresa Gresch"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Theresa Gresch"
	description = "Product Management / Software Development / QA Engineer"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "theresanew.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "<h1>Theresa Gresch</h1><h4>Freelance Product Manager</h4><h4>Software Engineer</h4><h4>Quality Advocate</h4>"
		# The icons will be shown if you enter your username
		twitter = ""
		github = "graciousgrey"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "theresa-gresch-886924103"

		copyright = [
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Hey."
		content = "<p>I'm a freelance product manager and quality advocate based in Berlin, Germany. Having worked with a number of startups makes me handle dynamic situations with ease. Customers also value my sense for usability and design.</p><p>Whenever there is an opportunity, I enjoy contributing to open-source projects to dive deeper into machine learning and improve my skills as developer.</p><h3>Skills & Experience</h3><p><ul><li>Project / Product Management</li><li>Agile Software Development, Scrum and Kanban</li><li>Acceptance and Unit Testing</li><li>Master of Science (M.Sc.) in Neurobiology</li></ul></p>"


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = ""
			thumb = ""
			title = "Product Development, Usability and Design - PhotoPrism.org"
			description = "Personal photo management powered by Go and Google TensorFlow. Free and open-source. Made with ❤️ in Berlin."

		[[params.portfolio.gallery]]
			image = ""
			thumb = ""
			title = "QA Manager - SinnerSchrader Deutschland GmbH"
			description = "Defined QA guidelines, set up automated tests, performed exploratory manual testing and instructed working students"

		[[params.portfolio.gallery]]
			image = ""
			thumb = ""
			title = "Product Manager - Pantaflix AG"
			description = "Responsible for tracking development progress, requirements management and enabling developers to work effectively. Enjoyed doing software development whenever there was an opportunity (Symfony. PHP, JS, Codeception, Docker)."

		[[params.portfolio.gallery]]
			image = ""
			thumb = ""
			title = "Quality Advocate - Mobomatic GmbH"
			description = "Requirements analysis, exploratory testing, debugging and bug-fixing together with a team of 6 developers."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Whatever it is, I’d love to hear from you!"
		content = "I'm currently available for freelance projects."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"Theresa Gresch",
			"Silbersteinstr. 85",
			"12051 Berlin"
		]
		phone = ""

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "theresagresch@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = ""
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "posts/"
	weight = 1
